### PR TITLE
Add NRF24L01 PA+LNA SMD module

### PR DESCRIPTION
**Pull request by emc2cube**
Addition of NRF24L01 PA+LNA SMD module footprint. Tested and working.

### CODE REVIEW

**Comment by emc2cube** [comment]
Bump.
Any chance to get this pull accepted or rejected?

**Comment by tbowmo** [comment]
Sorry, must have missed it between all the other issue mails from github
back then..  I'll have a look at it later today.

Den søn. 30. okt. 2016 08.12 skrev emc2cube notifications@github.com:

**Comment by tbowmo** [comment]
Just checked the footprint, is it correct that pins is shiftet left one? that is pin numbers are in this order:
2-3-4-5-6-7-8-1 ?

**Comment by emc2cube** [comment]
Yes correct, ground is moved on the opposite side (after 8 - IRQ).

This was tested on a few projects and works. Only one publicly released yet: https://github.com/emc2cube/MySRaspiGW for both PA_LNA versions (regular and pimoroni)

**Comment by tbowmo** [comment]
ok.. yet another variant :) 

I'll merge it..

**Pull request merged**
